pub const AGENTS_MD: &str = r#"<!-- core start -->

# Agent Workflow & Philosophy

You are a senior software engineer and project manager acting as a collaborative partner. Your goal is to maintain a high-quality codebase while keeping the project aligned with the user's vision.

## The Mental Model: "The Exosuit Way"

We build software by **Phased Evolution** of a **Living Context**, guided by **Immutable Axioms** and **User Intent**.

### 1. The Brain (Context)

**Principle**: "Context is King."
The `exo` CLI is the single source of truth for project state. We never guess; we read state through the tool.

- **Implication**: Every session starts with `exo status` and the relevant `exo` reads. Every action updates state through `exo` commands.

### 2. The Hands (Phases)

**Principle**: "Phased Execution."
We work in distinct, sequential phases (Plan -> Implement -> Verify). We never jump ahead.

- **Implication**: No code is written until the plan is approved. No phase is finished until verified.

### 3. The Memory (Documentation)

**Principle**: "Laws vs. Code."

- **RFCs are Laws**: Immutable records of decisions (History). Stage 3+ RFCs reflect implemented reality.
- **Implication**: You cannot "pass a law" (Stage 3/4 RFC) without implementing it first.

### 4. The Conscience (Alignment)

**Principle**: "User in the Loop."
The user is the ultimate arbiter. We stop for feedback at critical junctures.

- **Implication**: Use "Fresh Eyes" reviews to simulate user feedback.

---

## Operational Protocols

These protocols are derived from the Mental Model. Follow them to ensure consistency.

### Protocol: The Phase Loop

1.  **Start**: \`exo phase start <id>\`
2.  **Plan**:
    - **Update Plan**: Use \`exo task add "Task Name"\` to populate the plan.
    - **Draft**: Define tasks via \`exo task add\`. Stop for approval.
3.  **Implement**: Write code and tests.
    - **Document**: Record work via \`exo task\` commands.
4.  **Verify**: Run \`exo verify\`.
5.  **Commit**: Ensure all changes are committed. Use \`exo phase finish --message "..."\` to commit and finish in one step.
6.  **Finish**: \`exo phase finish\`.

### Protocol: The RFC Process (The Law)

1.  **Idea (Stage 0)**: Create \`docs/rfcs/stage-0/xxx-idea.md\`.
2.  **Proposal (Stage 1)**: Move to \`stage-1\`. Requires user approval.
3.  **Draft (Stage 2)**: Detailed spec. Requires user approval.
4.  **Candidate (Stage 3)**: Implemented.
5.  **Stable (Stage 4)**: Shipped.

**Rule**: Never promote Stage 0->1 or 1->2 without explicit instruction.

### Protocol: The Context Check

- **Read First**: Before answering, run `exo status` and `exo task list` to understand the current state.
- **Write Often**: Use `exo task add`, `exo task complete`, and `exo idea add` to keep state current.

### Protocol: Tool Usage

- **Structured IO**: When reading or modifying plan state, use the `exo-run` tool (e.g., `exo-run("status")`, `exo-run("task list")`). State is stored in SQLite; the tool is the source of truth.

---

## Reference: File Structure

- Exo operational state lives in SQLite and is exposed by `exo` commands.
- `docs/agent-context/`: Repo-policy SQL projection generated by `exo`; sidecar and shadow projects do not use it as a human-doc home.
- `docs/rfcs/`: Design decisions. Stage 3+ RFCs reflect implemented reality.
- `docs/research/`, `docs/design/`, `docs/specs/`: Durable human-authored notes and specifications.
- `exo`: The Tool. **Source of truth for plan, ideas, inbox, tasks.**
<!-- core end -->

# Project Mission

{{MISSION}}
"#;

pub const GITIGNORE: &str = r"# Exosuit standard .gitignore

# Build artifacts
target/
node_modules/
dist/
out/

# IDE and editor
.DS_Store
.vscode-test
*.vsix

# Logs
logs/
*.log

# TypeScript build artifacts
**/*.tsbuildinfo

# Coverage
lcov.info
coverage/

# Local environment
.direnv/
.env
.env.local

# Private/local files
.private/

# Exosuit temporary files
.context/temp/

# Exosuit local state (SQLite database, sockets, PIDs)
.exo/
.cache/
.runtime/
";

pub const GITATTRIBUTES: &str = r"# Repo-policy SQL projections are generated files. Sidecar and shadow policy
# projects do not write operational state into the workspace.
docs/agent-context/*.sql merge=exo-sql-dump
";

pub const SQL_DUMP_MERGE_DRIVER: &str = "exo-sql-dump";
pub const SQL_DUMP_MERGE_ATTRIBUTE: &str = "docs/agent-context/*.sql merge=exo-sql-dump";

pub const HOOKS_TOML: &str = r#"# Exosuit hooks configuration
# See: https://github.com/wycats/exo2/blob/main/docs/rfcs/stage-3/0137-exohook-ci-workflow-projection.md

version = 2

[defaults]
non_interactive = true
timeout_seconds = 900

[projections]

# Map git hooks to lanes.
[projections.git_hooks]
pre_commit = "coherence"
pre_push = "gate"

[lane.dev]
label = "Dev (uncommitted)"
description = "Run checks against uncommitted changes."
scope = { op = "base", base = "uncommitted" }
checks = ["check", "lint"]

[lane.coherence]
label = "pre-commit (staged)"
description = "Runs on the staged snapshot; mirrors the pre-commit hook."
scope = { op = "base", base = "staged" }
parallel = true
checks = ["check", "lint"]

[lane.gate]
label = "pre-push (committed not pushed)"
description = "Runs on commits that are local-only; mirrors the pre-push hook."
scope = { op = "base", base = "committed_not_pushed" }
parallel = true
checks = ["test"]

[check.check]
label = "Check"
description = "Typecheck / build checks across packages."
input_mode = "none"
run = "echo 'TODO: Add your typecheck command here'"

[check.lint]
label = "Lint"
description = "Lint checks across packages."
input_mode = "none"
run = "echo 'TODO: Add your lint command here'"

[check.test]
label = "Test"
description = "Run tests."
input_mode = "none"
run = "echo 'TODO: Add your test command here'"
"#;

struct PromptTemplate {
    filename: &'static str,
    contents: &'static str,
}

// These prompts are embedded from this repo's `.github/prompts` so `exo init`
// can scaffold new projects with a complete prompt set.
const PROJECT_PROMPTS: &[PromptTemplate] = &[
    PromptTemplate {
        filename: "bootstrap-axioms.prompt.md",
        contents: include_str!("../../../.github/prompts/bootstrap-axioms.prompt.md"),
    },
    PromptTemplate {
        filename: "conceptual-integrity.prompt.md",
        contents: include_str!("../../../.github/prompts/conceptual-integrity.prompt.md"),
    },
    PromptTemplate {
        filename: "dream-team-exosuit.prompt.md",
        contents: include_str!("../../../.github/prompts/dream-team-exosuit.prompt.md"),
    },
    PromptTemplate {
        filename: "fresh-eyes.prompt.md",
        contents: include_str!("../../../.github/prompts/fresh-eyes.prompt.md"),
    },
    PromptTemplate {
        filename: "gap-analysis.prompt.md",
        contents: include_str!("../../../.github/prompts/gap-analysis.prompt.md"),
    },
    PromptTemplate {
        filename: "persona-build.prompt.md",
        contents: include_str!("../../../.github/prompts/persona-build.prompt.md"),
    },
    PromptTemplate {
        filename: "prompt-builder.prompt.md",
        contents: include_str!("../../../.github/prompts/prompt-builder.prompt.md"),
    },
    PromptTemplate {
        filename: "troubleshoot-cli.prompt.md",
        contents: include_str!("../../../.github/prompts/troubleshoot-cli.prompt.md"),
    },
    // Coherence Matrix prompts
    PromptTemplate {
        filename: "coherence.prompt.md",
        contents: include_str!("../../../.github/prompts/coherence.prompt.md"),
    },
    PromptTemplate {
        filename: "coherence/check-axiomatic.prompt.md",
        contents: include_str!("../../../.github/prompts/coherence/check-axiomatic.prompt.md"),
    },
    PromptTemplate {
        filename: "coherence/check-intent.prompt.md",
        contents: include_str!("../../../.github/prompts/coherence/check-intent.prompt.md"),
    },
    PromptTemplate {
        filename: "coherence/check-internal.prompt.md",
        contents: include_str!("../../../.github/prompts/coherence/check-internal.prompt.md"),
    },
    PromptTemplate {
        filename: "coherence/check-temporal.prompt.md",
        contents: include_str!("../../../.github/prompts/coherence/check-temporal.prompt.md"),
    },
];

// Instruction files installed to .github/instructions/ for automatic injection
// These are exo-managed and separate from user's copilot-instructions.md
const INSTRUCTION_TEMPLATES: &[PromptTemplate] = &[PromptTemplate {
    filename: "exo-core.instructions.md",
    contents: include_str!("../../../src/templates/.github/instructions/exo-core.instructions.md"),
}];

/// Install exo instruction files to .github/instructions/
/// These are automatically injected by VS Code alongside user's copilot-instructions.md
pub fn install_instructions(root: &std::path::Path) -> Result<usize, std::io::Error> {
    let instructions_dir = root.join(".github/instructions");
    std::fs::create_dir_all(&instructions_dir)?;

    let mut written = 0usize;
    for instruction in INSTRUCTION_TEMPLATES {
        let path = instructions_dir.join(instruction.filename);
        if write_if_changed(&path, instruction.contents)? {
            written += 1;
        }
    }

    Ok(written)
}

pub fn install_project_prompts(root: &std::path::Path) -> Result<usize, std::io::Error> {
    let prompts_dir = root.join(".github/prompts");
    std::fs::create_dir_all(&prompts_dir)?;

    let mut written = 0usize;
    for prompt in PROJECT_PROMPTS {
        let path = prompts_dir.join(prompt.filename);
        // Create parent directories for nested prompts (e.g., coherence/check-*.prompt.md)
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        if write_if_changed(&path, prompt.contents)? {
            written += 1;
        }
    }

    Ok(written)
}

fn write_if_changed(path: &std::path::Path, contents: &str) -> Result<bool, std::io::Error> {
    let existing = std::fs::read_to_string(path).ok();
    if existing.as_deref() == Some(contents) {
        return Ok(false);
    }

    std::fs::write(path, contents)?;
    Ok(true)
}

// Request-scoped override used by daemon-routed CLI updates.
thread_local! {
    static GLOBAL_PROMPTS_HOME_OVERRIDE: std::cell::RefCell<Option<Option<std::path::PathBuf>>> =
        const { std::cell::RefCell::new(None) };
}

struct GlobalPromptsHomeOverrideGuard(Option<Option<std::path::PathBuf>>);

impl Drop for GlobalPromptsHomeOverrideGuard {
    fn drop(&mut self) {
        GLOBAL_PROMPTS_HOME_OVERRIDE.with(|home| {
            home.replace(self.0.take());
        });
    }
}

pub(crate) fn with_global_prompts_home_override<T>(
    home: Option<Option<std::path::PathBuf>>,
    operation: impl FnOnce() -> T,
) -> T {
    let previous = GLOBAL_PROMPTS_HOME_OVERRIDE.with(|current| current.replace(home));
    let _guard = GlobalPromptsHomeOverrideGuard(previous);
    operation()
}

/// Install global prompts to the user's VS Code prompts directory.
/// Path: `~/.config/Code/User/prompts/exo/`
pub fn install_global_prompts() -> Result<usize, std::io::Error> {
    let home =
        GLOBAL_PROMPTS_HOME_OVERRIDE.with(|override_home| match &*override_home.borrow() {
            Some(Some(home)) => Ok(home.clone()),
            Some(None) => Err(std::io::Error::new(
                std::io::ErrorKind::NotFound,
                "HOME environment variable not set for update caller",
            )),
            None => std::env::var("HOME")
                .map(std::path::PathBuf::from)
                .map_err(|_| {
                    std::io::Error::new(
                        std::io::ErrorKind::NotFound,
                        "HOME environment variable not set",
                    )
                }),
        })?;

    let global_prompts_dir = home.join(".config/Code/User/prompts/exo");
    std::fs::create_dir_all(&global_prompts_dir)?;

    let mut written = 0usize;
    for prompt in PROJECT_PROMPTS {
        let path = global_prompts_dir.join(prompt.filename);
        // Create parent directories for nested prompts
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        if write_if_changed(&path, prompt.contents)? {
            written += 1;
        }
    }

    Ok(written)
}

/// Install .gitignore with exosuit patterns.
pub fn install_gitignore(root: &std::path::Path) -> Result<bool, std::io::Error> {
    let path = root.join(".gitignore");
    write_if_changed(&path, GITIGNORE)
}

/// Install .gitattributes with generated SQL dump merge attributes.
pub fn install_gitattributes(root: &std::path::Path) -> Result<bool, std::io::Error> {
    let path = root.join(".gitattributes");
    write_if_changed(&path, GITATTRIBUTES)
}

/// Configure the repo-local merge driver for generated SQL dumps.
///
/// The driver intentionally exits successfully without touching `%A`, which
/// leaves the current branch version in place and marks generated dumps as
/// resolved during merges.
pub fn configure_sql_dump_merge_driver(root: &std::path::Path) -> Result<bool, std::io::Error> {
    if !is_git_worktree(root)? {
        return Ok(false);
    }

    let driver_key = format!("merge.{SQL_DUMP_MERGE_DRIVER}.driver");
    let name_key = format!("merge.{SQL_DUMP_MERGE_DRIVER}.name");
    let before_driver = git_config_get(root, &driver_key)?;
    let before_name = git_config_get(root, &name_key)?;

    git_config_set(
        root,
        &name_key,
        "Keep generated Exo SQL dump from current branch",
    )?;
    git_config_set(root, &driver_key, "true")?;

    Ok(before_driver.as_deref() != Some("true")
        || before_name.as_deref() != Some("Keep generated Exo SQL dump from current branch"))
}

/// Returns whether the repo-local SQL dump merge driver is configured.
pub fn sql_dump_merge_driver_configured(root: &std::path::Path) -> Result<bool, std::io::Error> {
    let Some(git_common_dir) = crate::project::git_common_dir_from_filesystem(root) else {
        return Ok(true);
    };

    let config = crate::git_config::read_repo_git_config(root, &git_common_dir.join("config"))?;
    Ok(
        crate::git_config::last_value(&config, "merge", Some(SQL_DUMP_MERGE_DRIVER), "driver")
            .is_some_and(|value| value.eq_ignore_ascii_case("true")),
    )
}

/// Install default hooks.toml.
pub fn install_hooks_toml(root: &std::path::Path) -> Result<bool, std::io::Error> {
    let path = root.join(".config/exo/hooks.toml");
    std::fs::create_dir_all(root.join(".config/exo"))?;
    write_if_changed(&path, HOOKS_TOML)
}

fn is_git_worktree(root: &std::path::Path) -> Result<bool, std::io::Error> {
    let output = std::process::Command::new("git")
        .arg("-C")
        .arg(root)
        .arg("rev-parse")
        .arg("--is-inside-work-tree")
        .output()?;

    Ok(output.status.success() && String::from_utf8_lossy(&output.stdout).trim() == "true")
}

fn git_config_get(root: &std::path::Path, key: &str) -> Result<Option<String>, std::io::Error> {
    let output = std::process::Command::new("git")
        .arg("-C")
        .arg(root)
        .arg("config")
        .arg("--local")
        .arg("--get")
        .arg(key)
        .output()?;

    if output.status.success() {
        Ok(Some(
            String::from_utf8_lossy(&output.stdout).trim().to_string(),
        ))
    } else {
        Ok(None)
    }
}

fn git_config_set(root: &std::path::Path, key: &str, value: &str) -> Result<(), std::io::Error> {
    let status = std::process::Command::new("git")
        .arg("-C")
        .arg(root)
        .arg("config")
        .arg("--local")
        .arg(key)
        .arg(value)
        .status()?;

    if status.success() {
        Ok(())
    } else {
        Err(std::io::Error::other(format!(
            "git config failed for {key}"
        )))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn merge_driver_detection_uses_the_last_repeated_section_value() {
        let temp = tempfile::tempdir().expect("create tempdir");
        let repo = temp.path();
        let status = std::process::Command::new("git")
            .arg("init")
            .arg(repo)
            .status()
            .expect("run git init");
        assert!(status.success());

        let config_path = repo.join(".git/config");
        let mut config = std::fs::read_to_string(&config_path).expect("read config");
        config.push_str(
            "\n[merge \"exo-sql-dump\"]\n\tdriver = false\n[merge \"exo-sql-dump\"]\n\tdriver = true\n",
        );
        std::fs::write(&config_path, config).expect("write config");

        assert!(sql_dump_merge_driver_configured(repo).expect("read merge driver"));
    }
}
