/**
 * TypeScript type definitions for command-spec.json
 *
 * This file provides type-safe access to the command specification artifact
 * generated by `exo json artifact`. The types mirror the Rust structs from
 * tools/exo/src/command/command_spec.rs.
 *
 * @see tools/exo/src/command/command_spec.rs - Source Rust definitions
 * @see RFC 0132 - CLI Patterns specification
 */

import commandSpecJson from "../command-spec.json";

/**
 * Effect classification for operations.
 *
 * - `pure`: Read-only operations with no side effects
 * - `write`: Operations that modify the workspace
 * - `exec`: Operations that execute external commands
 */
export type Effect = "pure" | "write" | "exec";

/** Recovery behavior when the daemon is replaced during a request. */
export type RecoveryClass =
  | "replayable_read"
  | "atomic_project_state"
  | "external_at_most_once";

/**
 * The kind of argument a command accepts.
 *
 * - `flag`: Boolean presence flag (e.g., `--verbose`)
 * - `option`: Key/value option (e.g., `--limit 20`)
 * - `positional`: Ordered positional argument
 */
export type ArgKind = "flag" | "option" | "positional";

/**
 * The type of an argument value.
 *
 * Values are typed at parse time per RFC 0132.
 */
export type ValueType =
  | "bool"
  | "int"
  | "float"
  | "string"
  | "path"
  | "json"
  | { enum: string[] };

/**
 * Specification for a command argument.
 *
 * Arguments come in three forms:
 * - Flag: boolean presence (`--verbose`)
 * - Option: key/value (`--limit 20`)
 * - Positional: ordered values
 */
export interface ArgSpec {
  /** Stable identifier for this argument */
  id: string;
  /** Display name (may differ from id for renames) */
  name: string;
  /** Human-readable description */
  description: string;
  /** The argument kind (flag, option, positional) */
  kind: ArgKind;
  /** The value type */
  value_type: ValueType;
  /** Whether this argument is optional */
  optional: boolean;
  /** Default value (if any) */
  default?: string;
  /** Short flag alias (e.g., "v" for "--verbose") */
  short?: string;
}

/**
 * LM tool presentation metadata for package.json contributions.
 */
export interface LmToolMetadata {
  /** Human-readable tool display name */
  displayName?: string;
  /** Full model-facing description */
  modelDescription?: string;
  /** Short user-facing description */
  userDescription?: string;
  /** VS Code icon identifier */
  icon?: string;
  /** Optional when clause for activation */
  when?: string;
  /** Tool reference name for prompts */
  toolReferenceName?: string;
  /** Optional tags for discovery */
  tags?: string[];
  /** Whether the tool can be referenced in prompts */
  canBeReferencedInPrompt?: boolean;
}

/**
 * Specification for a single operation.
 *
 * An operation is a leaf command that performs an action.
 * For example: `phase start`, `task complete`, `rfc create`.
 */
export interface OperationSpec {
  /** The operation name (e.g., "start", "complete") */
  name: string;
  /** Human-readable description */
  description: string;
  /** Effect classification (pure, write, exec) */
  effect: Effect;
  /** Recovery behavior after daemon replacement */
  recovery_class: RecoveryClass;
  /** Whether this operation requires an upgrade gate check */
  needs_upgrade_gate: boolean;
  /** Arguments this operation accepts */
  args: ArgSpec[];
  /** Example usage (optional) */
  example?: string;
  /** LM tool metadata (optional) */
  lm_tool?: LmToolMetadata;
}

/**
 * Specification for a command namespace.
 *
 * A namespace groups related operations. For example:
 * - `phase` contains `start`, `finish`, `status`
 * - `task` contains `add`, `complete`, `list`
 */
export interface NamespaceSpec {
  /** The namespace name (e.g., "phase", "task") */
  name: string;
  /** Human-readable description of the namespace */
  description: string;
  /** Operations in this namespace */
  operations: Record<string, OperationSpec>;
}

/**
 * The root specification for all commands.
 *
 * CommandSpec organizes commands hierarchically by namespace, then operation.
 * This mirrors the CLI structure: `exo <namespace> <operation> [args...]`
 */
export interface CommandSpec {
  /** Version of the spec format (for forward compatibility) */
  version: number;
  /** Map from namespace name to namespace specification */
  namespaces: Record<string, NamespaceSpec>;
  /** Root operations without a namespace (e.g., status, map) */
  root_operations: Record<string, OperationSpec>;
  /** Total count of operations across all namespaces */
  operation_count?: number;
  /** Generation marker (present in JSON but not part of schema) */
  _generated?: string;
}

/**
 * Load and validate the command specification.
 *
 * This function loads the auto-generated command-spec.json and provides
 * type-safe access to the command tree. The JSON file contains the
 * CommandSpec directly (generated by `exo json artifact`).
 *
 * @returns The parsed and typed command specification
 *
 * @example
 * ```typescript
 * const spec = loadCommandSpec();
 * const phaseStart = spec.namespaces.phase?.operations.start;
 * if (phaseStart) {
 *   console.log(`Effect: ${phaseStart.effect}`);
 *   console.log(`Args: ${phaseStart.args.length}`);
 * }
 * ```
 */
export function loadCommandSpec(): CommandSpec {
  // The JSON is validated at build time by Rust serialization.
  // command-spec.json contains the CommandSpec directly from `exo json artifact`.
  return commandSpecJson as CommandSpec;
}

/**
 * Get a namespace by name.
 *
 * @param namespaceName - The name of the namespace to retrieve
 * @returns The namespace spec, or undefined if not found
 */
export function getNamespace(namespaceName: string): NamespaceSpec | undefined {
  const spec = loadCommandSpec();
  return spec.namespaces[namespaceName];
}

/**
 * Get an operation by fully-qualified name.
 *
 * @param namespace - The namespace name
 * @param operation - The operation name
 * @returns The operation spec, or undefined if not found
 */
export function getOperation(
  namespace: string,
  operation: string,
): OperationSpec | undefined {
  const ns = getNamespace(namespace);
  return ns?.operations[operation];
}

/**
 * Get a root operation by name.
 *
 * @param operation - The root operation name
 * @returns The operation spec, or undefined if not found
 */
export function getRootOperation(operation: string): OperationSpec | undefined {
  const spec = loadCommandSpec();
  return spec.root_operations[operation];
}

/**
 * Check if an operation qualifies for zero-arg LM tool projection.
 *
 * Per RFC 0132, an operation qualifies if:
 * - Effect is Pure (no side effects)
 * - All arguments are optional or have defaults
 *
 * @param op - The operation spec to check
 * @returns True if the operation can be called with zero arguments
 */
export function isZeroArg(op: OperationSpec): boolean {
  return (
    op.effect === "pure" &&
    op.args.every((arg) => arg.optional || arg.default !== undefined)
  );
}

/**
 * Get all operations across all namespaces.
 *
 * @returns Array of tuples: [namespace, operationName, operationSpec]
 */
export function getAllOperations(): Array<
  [namespace: string, operationName: string, operation: OperationSpec]
> {
  const spec = loadCommandSpec();
  const result: Array<[string, string, OperationSpec]> = [];

  for (const [opName, op] of Object.entries(spec.root_operations)) {
    // getAllOperations
    result.push(["", opName, op]);
  }

  for (const [nsName, ns] of Object.entries(spec.namespaces)) {
    for (const [opName, op] of Object.entries(ns.operations)) {
      result.push([nsName, opName, op]);
    }
  }

  return result;
}

/**
 * Get all canonical tool names derived from the command spec.
 *
 * This includes root operations (`exo-status`) and namespace operations
 * (`exo-phase-start`).
 */
export function getCommandSpecToolNames(): string[] {
  const spec = loadCommandSpec();
  const toolNames: string[] = [];

  for (const opName of Object.keys(spec.root_operations)) {
    toolNames.push(`exo-${opName}`);
  }

  for (const [namespace, ns] of Object.entries(spec.namespaces)) {
    for (const opName of Object.keys(ns.operations)) {
      toolNames.push(`exo-${namespace}-${opName}`);
    }
  }

  return toolNames;
}
